@SimpleChatServer_HostAddress = https://localhost:7241

POST {{SimpleChatServer_HostAddress}}/api/login
Accept: application/json
Content-Type: application/json

{
    "username": "adam",
    "password": "1234"
}
